spring.application.name=financeControl

# Conexão com o Banco
spring.datasource.url=jdbc:postgresql://localhost:5433/finance_db
spring.datasource.username=postgres
spring.datasource.password=admin

# Estratégia do Hibernate (Cria as tabelas automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Chave de segurança do token de validação
api.security.token.secret=${JWT_SECRET:frase-secreta-de-senha-forte-aqui-123}